### ISSUE TITLE
Small tweaks

### ISSUE THREAD

**Issue by E-A-A** [mortorqrobotics/morteam-web#18]
This involves fixing many small problems before launch:

note: no new problems should be added to this issue

- [x] 1. announcement text box does not resize when window is made smaller
- [x] 2. announcement textbox does not go to next line at end of box
- [x] 3. announcement page doesn't collapse for appropriate mobile view
- [x] 4. announcement dates are incorrect
- [x] 5. clicking on the person who posted announcement does nothing
- [x] 6. 'post' button never enables
- [x] 7. chat textbox does not scroll vertically
- [x] 8. select audience should be drop down first with a custom choice
- [x] 9. user search dropdown should have backdrop shadow
- [x] 10. copyright 2016 (not 2015)
- [x] 11. lighter dark overlays for modals and profile settings dropdown
- [x] 12. certain buttons are styled with a border (not consistent)
- [x] 13. chat textbox and send button are elevated and have weird borders
- [x] 14. topmost item of navbar search dropdown lacks a top border
- [x] 15. chat textbox has weird highlight when focused (possibly mac only)
- [x] 16. when navbar dropdown is open, navbar drop shadow is not visible
- [x] 17. timestamps on hover have not been implemented
- [x] 18. mobile menu bar has not been implemented
- [x] 19. drive folders are not in order
- [x] 20. drive area does not expand when left bar is collapsed 
      (try collapsing left bar and resizing window with a few files in it)
- [x] 22. if its possible remove lag when scrolling between two months
- [x] 23. make current day appear about 30px below its current position
- [x] 24. upcoming events disappears under certain window size but does not expand timeline view
- [x] 25. left bar does not re appear after its been collapsed when clicking on a team on map
- [x] 26. attendance and tasks boxes should have shadows 
- [x] 27. attendance and tasks boxes should have more top margin
- [x] 28. does not indicate empty 'pending' tasks
- [x] 29. 'pending' font is smaller than 'completed' font
- [x] 30. round attendance to nearest integer or tenth
- [x] 31. solution for long names in team/subdiv pages?
- [x] 32. weird margins (not centered) for the blocks in the team/subdiv pages

**Comment by AriellaS** [comment]
in addition:
when navbar dropdown is open, navbar drop shadow is not visible
topmost item of navbar search dropdown lacks a top border

**Comment by afuous** [comment]
See https://github.com/mortorqrobotics/morteam-web/commits/pre-launch-tweaks.

**Comment by afuous** [comment]
32 is being addressed in another pull request #7.

**Comment by afuous** [comment]
29 is simply false; they are both 20px.

**Comment by E-A-A** [comment]
15 was solved by addition of outline: none to text area.

**Comment by E-A-A** [comment]
7 is not a small tweak and will be addressed in issue #28.

**Comment by E-A-A** [comment]
3d84fe68 solves number 14

**Comment by AriellaS** [comment]
ac57368 solves 17

**Comment by AriellaS** [comment]
3d84fe6 solves 14

**Comment by afuous** [comment]
8 is being addressed in #30.

**Comment by afuous** [comment]
1, 3, 22, 24, 31 have been moved to #31 as 14 to 18.
