### ISSUE TITLE
Prevent messages from jumping up and down by reserving bottommost row for typing indicator

### ISSUE THREAD

**Issue by Farbod909** [mortorqrobotics/morteam-web#29]
if the bottommost row is reserved for a typing indicator then the quick changes in "is typing" and not "is typing" would not cause the other messages to jump up and down.

**Comment by afuous** [comment]
This is being addressed [here](https://github.com/mortorqrobotics/morteam-web/tree/hide-typing-indicator).

**Comment by Farbod909** [comment]
Additional thoughts:
- Create said 'reserved' row only after someone has started typing and remove it when any new message is received.
- Do not remove said row if the is typing indicator was shown and then removed.
