### ISSUE TITLE
Additional tweaks

### ISSUE THREAD

**Issue by Farbod909** [mortorqrobotics/morteam-web#31]
- [x] 1. chat textbox still elevated
- [x] 2. configuration station folder is always selected first (is this arbitrary?)
- [x] 3. Other groups doesn’t show up?
- [x] 4. for chat notifications with jbox, chat name is showing up as undefined
- [x] 5. ‘post’ button enables even if nothing is selected after opening audience modal
- [x] 6. drive folders still not in order
- [x] 7. there should be an hr element between pending and completed tasks
- [x] 8. when changing chat name to a string larger than 19 characters an error should be shown and the contents of the textbox should be reverted when the modal is reopened
- [x] 9. make people and groups listed in chat options clickable
- [x] 10. online/offline indicator for people listed in chat options
- [x] 11. show notifications for other chats while user is in a different chat on the chat page
- [x] 12. select most recently selected chat on reload, as opposed to topmost chat
- [x] 13. clicking gear icon should not select chat
- [x] 14. announcement text box does not resize when window is made smaller
- [x] 15. announcement page doesn't collapse for appropriate mobile view
- [x] 16. if it's possible remove lag when scrolling between two months
- [x] 17. upcoming events disappears under certain window size but does not expand timeline view
- [x] 18. solution for long names in team/subdiv pages?
- [x] 19. navbar dropdwon items should change color on hover

**Comment by afuous** [comment]
3 was addressed by #35.

**Comment by AriellaS** [comment]
2 and 6 solved by 09a3a6c

**Comment by AriellaS** [comment]
4 solved by https://github.com/mortorqrobotics/morteam-server-website/commit/60ab5ea87cf5ce65106b54523a84574af9f5bc97

**Comment by E-A-A** [comment]
14 and 15 solved by 3874fa9

**Comment by AriellaS** [comment]
16 is being addressed in #52

**Comment by AriellaS** [comment]
18 is being addressed in #53
